const REQUEST_TYPES = {
  COACH: "COACH",
  SERVICE: "SERVICE",
  APPOINTMENT: "APPOINTMENT",
};

const REQUEST_STATUSES = {
  NEW: "NEW",
  READ: "READ",
  ANSWERED: "ANSWERED",
  ACCEPTED: "ACCEPTED",
  DISCARDED: "DISCARDED",
};

const SEEN_REQUEST_STATUSES = {
  NEW: "NEW",
  READ: "READ",
};

module.exports = { REQUEST_STATUSES, REQUEST_TYPES, SEEN_REQUEST_STATUSES };
